---
# tasks file for opentelekomcloud_infra.sync_servers

- name: Generate ssh key
  openssh_keypair:
    path: "~/.ssh/id_rsa"
  register:
    ssh_key

- name: Save public key
  set_fact:
    ssh_key: "{{ ssh_key.public_key }}"


