---
# tasks file for opentelekomcloud_infra.server_sync
- name: Generate ssh key
  become: true
  openssh_keypair:
    path: "~/.ssh/id_rsa"
  register:
    ssh_key

- name: Save public key
  set_fact:
    ssh_key: "{{ ssh_key.public_key }}"
